=== laureano57/INSPT-S1-TPs/tps/tp4/definitions.dtd
<!ELEMENT data (codes, petherick-code)>
<!ELEMENT codes (row*)>
<!ELEMENT row (position, gray, glixon, obrien, obrien2, excessGray, tompkins, tompkins2, petherick, libaw-craig)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT gray (#PCDATA)>
<!ELEMENT glixon (#PCDATA)>
<!ELEMENT obrien (#PCDATA)>
<!ELEMENT obrien2 (#PCDATA)>
<!ELEMENT excessGray (#PCDATA)>
<!ELEMENT tompkins (#PCDATA)>
<!ELEMENT tompkins2 (#PCDATA)>
<!ELEMENT libaw-craig (#PCDATA)>
<!ELEMENT petherick-code (petherick-row*)>
<!ELEMENT petherick-row (position, petherick0, petherick1)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT petherick0 (#PCDATA)>
<!ELEMENT petherick1 (#PCDATA)>

=== laureano57/INSPT-S1-TPs/tps/tp4/index.xml
<?xml version = "1.0" encoding = "iso-8859-1" ?>
<?xml-stylesheet type = "text/xsl" href = "styles.xsl"?>
<!DOCTYPE codes SYSTEM "definitions.dtd">

<codes>
  <row>
    <position>0</position>
    <gray>0000</gray>
    <glixon>0000</glixon>
    <obrien>0000</obrien>
    <obrien2>0001</obrien2>
    <excessGray>0010</excessGray>
    <tompkins>0000</tompkins>
    <tompkins2>0010</tompkins2>
    <petherick>0101</petherick>
  </row>
  <row>
    <position>1</position>
    <gray>0001</gray>
    <glixon>0001</glixon>
    <obrien>0001</obrien>
    <obrien2>0011</obrien2>
    <excessGray>0110</excessGray>
    <tompkins>0001</tompkins>
    <tompkins2>0011</tompkins2>
    <petherick>0001</petherick>
  </row>
  <row>
    <position>2</position>
    <gray>0011</gray>
    <glixon>0011</glixon>
    <obrien>0011</obrien>
    <obrien2>0010</obrien2>
    <excessGray>0111</excessGray>
    <tompkins>0011</tompkins>
    <tompkins2>0111</tompkins2>
    <petherick>0011</petherick>
  </row>
  <row>
    <position>3</position>
    <gray>0010</gray>
    <glixon>0010</glixon>
    <obrien>0010</obrien>
    <obrien2>0110</obrien2>
    <excessGray>0101</excessGray>
    <tompkins>0010</tompkins>
    <tompkins2>0101</tompkins2>
    <petherick>0010</petherick>
  </row>
  <row>
    <position>4</position>
    <gray>0110</gray>
    <glixon>0110</glixon>
    <obrien>0110</obrien>
    <obrien2>0100</obrien2>
    <excessGray>0100</excessGray>
    <tompkins>0110</tompkins>
    <tompkins2>0100</tompkins2>
    <petherick>0110</petherick>
  </row>
  <row>
    <position>5</position>
    <gray>0111</gray>
    <glixon>0111</glixon>
    <obrien>1110</obrien>
    <obrien2>1100</obrien2>
    <excessGray>1100</excessGray>
    <tompkins>1110</tompkins>
    <tompkins2>1100</tompkins2>
    <petherick>1110</petherick>
  </row>
  <row>
    <position>6</position>
    <gray>0101</gray>
    <glixon>0101</glixon>
    <obrien>1010</obrien>
    <obrien2>1110</obrien2>
    <excessGray>1101</excessGray>
    <tompkins>1111</tompkins>
    <tompkins2>1101</tompkins2>
    <petherick>1010</petherick>
  </row>
  <row>
    <position>7</position>
    <gray>0100</gray>
    <glixon>0100</glixon>
    <obrien>1011</obrien>
    <obrien2>1010</obrien2>
    <excessGray>1111</excessGray>
    <tompkins>1101</tompkins>
    <tompkins2>1001</tompkins2>
    <petherick>1011</petherick>
  </row>
  <row>
    <position>8</position>
    <gray>1100</gray>
    <glixon>1100</glixon>
    <obrien>1001</obrien>
    <obrien2>1011</obrien2>
    <excessGray>1110</excessGray>
    <tompkins>1100</tompkins>
    <tompkins2>1011</tompkins2>
    <petherick>1001</petherick>
  </row>
  <row>
    <position>9</position>
    <gray>1101</gray>
    <glixon>1000</glixon>
    <obrien>1000</obrien>
    <obrien2>1001</obrien2>
    <excessGray>1010</excessGray>
    <tompkins>1000</tompkins>
    <tompkins2>1010</tompkins2>
    <petherick>1101</petherick>
  </row>
</codes>
